# Generated by Django 4.2.2 on 2023-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslapp', '0002_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cname',
            field=models.TextField(default='Karthika'),
        ),
    ]
